name: AdvancedBan
version: ${project.version}
main: ${project.groupId}.bukkit.BukkitMain
author: Leoko
softdepend: [Vault]
api-version: 1.13

commands:
  AdvancedBan:
    description: Information about the Plugin
  localban:
    description: Ban a user permanently
  localtempban:
    description: Ban a user temporarily
  localipban:
    description: Ban a user by IP
    aliases: [localbanip, localban-ip]
  localtempipban:
    description: Ban a user temporarily by IP
    aliases: [localtipban]
  localkick:
    description: Kick a user
  localwarn:
    description: Warn a user permanently
  localnote:
    description: Adds a note to a users file
  localtempwarn:
    description: Warn a user temporarily
  localmute:
    description: Mute a user permanently
  localtempmute:
    description: Mute a user temporarily
  localbanlist:
    description: See all punishments
  localhistory:
    description: See a user''s history
  localwarns:
    description: See your or a user''s warns
  localnotes:
    description: See your or a user''s notes
  localcheck:
    description: Get all information about a user
  localsystemPrefs:
    description: Displays System-Preferences for setting up the plugin
  localunwarn:
    description: Deletes a warn
  localunnote:
    description: Deletes a note
  localunpunish:
    description: Deletes a punishment by ID
  localunban:
    description: Unban a user
  localunmute:
    description: Unmute a user
  localchangereason:
    description: Change the reason of an existing punishment